-- begin TASKMAN_TASK
alter table TASKMAN_TASK add constraint FK_TASKMAN_TASK_ON_ASSIGNEE foreign key (ASSIGNEE_ID) references SEC_USER(ID)^
create unique index IDX_TASKMAN_TASK_UK_NUMBER_ on TASKMAN_TASK (NUMBER_) where DELETE_TS is null ^
create index IDX_TASKMAN_TASK_ON_ASSIGNEE on TASKMAN_TASK (ASSIGNEE_ID)^
-- end TASKMAN_TASK
-- begin TASKMAN_TASK_MESSAGE
alter table TASKMAN_TASK_MESSAGE add constraint FK_TASKMAN_TASK_MESSAGE_ON_TASK foreign key (TASK_ID) references TASKMAN_TASK(ID)^
alter table TASKMAN_TASK_MESSAGE add constraint FK_TASKMAN_TASK_MESSAGE_ON_IMAP_MESSAGE foreign key (IMAP_MESSAGE_ID) references IMAP_MESSAGE(ID)^
create index IDX_TASKMAN_TASK_MESSAGE_ON_TASK on TASKMAN_TASK_MESSAGE (TASK_ID)^
create index IDX_TASKMAN_TASK_MESSAGE_ON_IMAP_MESSAGE on TASKMAN_TASK_MESSAGE (IMAP_MESSAGE_ID)^
create index INDX_TASKMAN_TASK_MESSAGE_ON_ORIGINAL_IMAP_MESSAGE_ID on TASKMAN_TASK_MESSAGE (ORIGINAL_IMAP_MESSAGE_ID) ^
-- end TASKMAN_TASK_MESSAGE
